### ISSUE TITLE
Issues when following the readme

### ISSUE THREAD

**Issue by Metaxal** [camall3n/focused-macros#2]
Hello there,

First of all, thanks for this project and the paper, it's a cool idea and a nice read.

I'm following the readme, but got stuck here:
```shell
(venv) $ pip install -r requirements.txt 
ERROR: git+git@github.com:camall3n/pddlgym.git@6f75090ad96a79a23bbb8b34c3d20ec6110572df#egg=pddlgym is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

Any clue?

(Also, maybe it should be mentioned that `python3-venv` should be installed, e.g. `sudo apt-get install -y python3-venv`.)

Thanks!

**Comment by camall3n** [comment]
Looks like it could be a git permissions thing. Try editing `requirements.txt` and changing this line
```text
-e git+git@github.com:camall3n/pddlgym.git@6f75090ad96a79a23bbb8b34c3d20ec6110572df#egg=pddlgym
```
to the following:
```text
-e git+https://github.com/camall3n/pddlgym.git@6f75090ad96a79a23bbb8b34c3d20ec6110572df#egg=pddlgym
```

**Comment by Metaxal** [comment]
Same issue

**Comment by camall3n** [comment]
With the virtual environment activated, try running:
```bash
python3 -m pip install -e git+https://github.com/camall3n/pddlgym.git@6f75090ad96a79a23bbb8b34c3d20ec6110572df#egg=pddlgym
```
by itself, and then installing the remaining requirements with `-r requirements.txt`.

Btw, the PDDLGym requirement was only for the IPC experiments. The Rubik's cube and 15-puzzle experiments should ideally still work if you comment out line 23 of `requirements.txt`.

**Comment by camall3n** [comment]
If that fails, you might also try `python3 -m pip install -e ./pddlgym`, assuming you successfully pulled down the submodules.

**Comment by Metaxal** [comment]
Ah, that works now. Although indeed I only wanted to try out the rubik's cube :) 

But now I get a bunch of errors when installing numpy (via scipy) that seems unrelated to your codebase:
```
           numpy/core/src/multiarray/scalartypes.c.src:3258:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
             3258 |     return _Py_HashDouble(npy_half_to_double(((PyHalfScalarObject *)obj)->obval));
                  |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  |                           |
                  |                           double
 ```

**Comment by camall3n** [comment]
Great, hopefully you can get the numpy issues resolved!
